#TODO
FROM openjdk:11
COPY build/libs/ /var/www/java
WORKDIR /var/www/java
CMD ["chmod","+x","Codejam-Assignments-Solutions-1.0-SNAPSHOT.jar"]
CMD ["java","-jar","Codejam-Assignments-Solutions-1.0-SNAPSHOT.jar"]