pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    chmod +x gradlew
                    echo "I am in build step"
                    ./gradlew
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    chmod +x gradlew
                    echo "I am in Test step"
                    ./gradlew clean test
                    ls
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage"
                    docker build -t varunnayal/play_with_codejam_assignments:version1.0 .infra/docker/
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage"
                    docker push varunnayal/play_with_codejam_assignments:version1.0
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
    post {
    	always {
		deleteDir()
		}
	}
}

