pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    chmod +x gradlew
                    echo "I am in build step"
                    ./gradlew build -x test
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    chmod +x gradlew
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "c26e46035bf469f1cb43a7e301763680a8fdda2f"
                    echo "I am in Sonarqube scan"
                ''',
                withSonarQubeEnv() { // Will pick the global server connection you have configured
                     sh './gradlew sonarqube'
                   }
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage"
                    docker build -t varunnayal/play_with_codejam_assignments:version1.0 -f ./.infra/docker/Dockerfile .
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage"
                    docker login -u varunnayal -p rcmadasgupta
                    docker push varunnayal/play_with_codejam_assignments:version1.0
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
    post{
    	   always{
    	     deleteDir()
    	   }
    }
}

